export const PLACEHOLDER_PRODUCTS = [
  {
    id: 1,
    name: "Noise-Canceling Headphones",
    price: 29999,
    category: "Audio",
    description: "Premium wireless headphones with active noise cancellation.",
    image: null,
  },
  {
    id: 2,
    name: "Mechanical Keyboard",
    price: 15499,
    category: "Tech",
    description: "RGB mechanical keyboard with blue switches.",
    image: null,
  },
  {
    id: 3,
    name: "Smart Watch Series 5",
    price: 45000,
    category: "Tech",
    description: "Advanced fitness tracking and notifications.",
    image: null,
  },
  {
    id: 4,
    name: "Gaming Mouse",
    price: 8500,
    category: "Gaming",
    description: "High-precision optical sensor gaming mouse.",
    image: null,
  },
  {
    id: 5,
    name: "4K Monitor 27inch",
    price: 120000,
    category: "Tech",
    description: "Ultra HD display for professional creative work.",
    image: null,
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    price: 12500,
    category: "Audio",
    description: "Portable speaker with deep bass and long battery life.",
    image: null,
  },
  {
    id: 7,
    name: "Laptop Stand",
    price: 5000,
    category: "Accessories",
    description: "Ergonomic aluminum laptop stand.",
    image: null,
  },
  {
    id: 8,
    name: "Coffee Maker",
    price: 25000,
    category: "Appliance",
    description: "Programmable coffee maker for the perfect brew.",
    image: null,
  },
];
